# Generated by Django 4.0.3 on 2023-03-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(default='HH:MM', help_text='Enter time as HH:MM'),
        ),
    ]
